version: 1.0.{build}
environment:
  NUGET_SOURCE:
    secure: qecpY2iYmZmFJjCKF/g+khFJXI17P9b2JM2KygVYGkS/MdVNhVOXTt6JO3+qf5K6
  GITHUB_USERNAME:
    secure: /eFWOKC5WlTCsjmVXOrmiX/u3GtrjGzDj4kBxDw6PbI=
  GITHUB_TOKEN:
    secure: mMrrEYoa3W9aMdthNtjHA9+FfEoYc3rcg7QW2lqvjZQ=
  NUGET_APIKEY:
    secure: ilgXixdHFR4fmcNjBiIB3686iIKTDToC1q7mAEsgyqM/Umuq9P20BiHSKRcY3J1R
build_script:
- ps: ./build.ps1 -Verbosity Diagnostic
test: off
artifacts:
- path: '**/bin/*'
- path: artifacts/*
