//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("SushiHangover.Cake.AppleSimulator")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0")]
[assembly: AssemblyInformationalVersion("0.1.0-sushi.1+6.Branch.sushi.Sha.6bd82694372f6c3eccf6052ef1b14b5385e41db3")]
[assembly: AssemblyCopyright("Copyright (c) SushiHangover/RobertN")]

