//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Cake.AppleSimulator.SushiHangover")]
[assembly: AssemblyVersion("0.2.1")]
[assembly: AssemblyFileVersion("0.2.1")]
[assembly: AssemblyInformationalVersion("0.2.1+Branch.sushi.Sha.5ddee3e53349e2b35699625f67578d89cfba200f")]
[assembly: AssemblyCopyright("Copyright (c) SushiHangover/RobertN")]

