//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("SushiHangover.Cake.AppleSimulator")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0")]
[assembly: AssemblyInformationalVersion("0.1.0-sushi.1+7.Branch.sushi.Sha.e8ec3aeaa7c20dd589e5adce554bb10c40390196")]
[assembly: AssemblyCopyright("Copyright (c) SushiHangover/RobertN")]

